### ISSUE TITLE
need doc for adding certs to registry

### ISSUE THREAD

**Issue by bparees** [openshift/openshift-docs#8375]
### Which section(s) is the issue in?
https://docs.openshift.org/latest/install_config/registry/extended_registry_configuration.html#middleware-repository-pullthrough

### What needs fixing?
Need to discuss the problem of ensuring your registry has appropriate certs to trust any external registries you may end up doing a pullthrough against.  The certs need to be placed in the /etc/pki/tls/certs dir within the pod.  Most likely this means mounting them in via a configmap or secret, but the entire dir must be replaced, so you can't just add your new certs, you also need to include the system certs in your secret/configmap that is being mounted.

**Comment by vikram-redhat** [comment]
@bparees is any of this solved by this PR that @mburke5678 has been working on? https://github.com/openshift/openshift-docs/pull/7607

Or can that be merged with that work?

**Comment by bparees** [comment]
@vikram-redhat totally unrelated.

**Comment by vikram-redhat** [comment]
@bparees - thanks. @mburke5678 - can you still work on this with @dmage

**Comment by mburke5678** [comment]
Documentation started in https://github.com/openshift/openshift-docs/pull/8671

@dmage Any help with this would be greatly appreciated.

**Comment by Klaas-** [comment]
So I followed the doc from #8671 and add my pki certs via configmap to the docker-registry deployment config. I still get an error like this on 
```
# oc import-image httpd -n openshift
[...]
! error: Import failed (InternalError): Internal error occurred: Get https://access.redhat.com/webassets/docker/content/dist/rhel/server/7/7Server/multiarch/rhscl/1/containers/registry/rhscl/httpd-24-rhel7/manifests/list/latest: x509: certificate signed by unknown authority
```

I tried manually with rsh inside one of the registry containers and curl works fine. Side note: this is an ssl interception proxy we have to use.

Are there other certificate stores the registry uses that I need to modify? Are there more pods that need modifying?

**Comment by bparees** [comment]
image import is unrelated to the registry.

image import is handled by the api server, so your api server process must have appropriate certificates as well.

this is where the "AdditionalTrustedCA" configuration setting can be used:
https://docs.okd.io/latest/install_config/master_node_configuration.html#master-config-image-policy-config

**Comment by Klaas-** [comment]
Thanks @bparees I'll give it a try
